# Generated by Django 3.2.4 on 2021-07-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['User_Name']},
        ),
        migrations.RemoveField(
            model_name='register',
            name='Confirm_mail',
        ),
    ]
