# Generated by Django 3.2.4 on 2021-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210701_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['mail'],
            },
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
