# Generated by Django 3.2.5 on 2021-07-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210701_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registermodel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='registermodel',
            name='password',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
