# Generated by Django 3.2.5 on 2021-07-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_registermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
